# vim: set sts=2 ts=2 sw=2 et:

function(CS2FOW_json_string json_content out_var)
    set(_keys ${ARGN})
    string(JSON _value ERROR_VARIABLE _err GET "${json_content}" ${_keys})
    if (_err)
        return()
    endif ()
    set(${out_var} "${_value}" PARENT_SCOPE)
endfunction()


function(CS2FOW_json_string_array json_content out_var)
    set(_keys ${ARGN})
    string(JSON _len ERROR_VARIABLE _err LENGTH "${json_content}" ${_keys})
    if (_err)
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif ()
    set(_result "")
    if (_len GREATER 0)
        math(EXPR _last "${_len} - 1")
        foreach (_i RANGE 0 ${_last})
            string(JSON _item GET "${json_content}" ${_keys} ${_i})
            list(APPEND _result "${_item}")
        endforeach ()
    endif ()
    set(${out_var} "${_result}" PARENT_SCOPE)
endfunction()
